---
- name: Install 
  ansible.builtin.apt:
    pkg:
    - htop
  become: true
  when: ubuntu_default not in common

- include_tasks: "common/{{ubuntu_default}}/main.yml"
  when: ubuntu_default in common